from pathlib import Path
import pickle

import pandas as pd
import streamlit as st


MODEL_PATH = Path(__file__).resolve().parent / "iris_model.pkl"
FEATURE_COLUMNS = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
]


@st.cache_resource
def load_model():
    if not MODEL_PATH.exists():
        return None, None, None

    try:
        with MODEL_PATH.open("rb") as file:
            payload = pickle.load(file)
    except Exception as exc:  # pragma: no cover - UI handling
        st.error(f"Unable to load model file: {exc}")
        return None, None, None

    if isinstance(payload, dict):
        model = payload.get("model")
        accuracy = payload.get("accuracy")
        target_names = payload.get("target_names", ["setosa", "versicolor", "virginica"])
        return model, accuracy, target_names

    return payload, None, ["setosa", "versicolor", "virginica"]


st.set_page_config(page_title="Iris Flower Classification", layout="wide")

# Hide the default Streamlit deploy button from the top-right app menu.
st.markdown(
    """
    <style>
    [data-testid="stHeaderActionElements"] {display: none;}
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("Iris Flower Classification")
st.subheader("Cloud-Based Machine Learning Model Deployment")
st.write(
    "This application uses a Random Forest machine learning model trained on the Iris dataset "
    "to classify flower species from sepal and petal measurements."
)

model, accuracy, target_names = load_model()

if model is None:
    st.error("Model file not found. Please run train_model.py first.")
    st.stop()

col1, col2 = st.columns(2)
with col1:
    sepal_length = st.number_input(
        "Sepal Length (cm)",
        min_value=0.0,
        max_value=10.0,
        value=5.1,
        step=0.1,
    )
    petal_length = st.number_input(
        "Petal Length (cm)",
        min_value=0.0,
        max_value=10.0,
        value=1.4,
        step=0.1,
    )
with col2:
    sepal_width = st.number_input(
        "Sepal Width (cm)",
        min_value=0.0,
        max_value=10.0,
        value=3.5,
        step=0.1,
    )
    petal_width = st.number_input(
        "Petal Width (cm)",
        min_value=0.0,
        max_value=10.0,
        value=0.2,
        step=0.1,
    )

st.markdown("---")

if st.button("Predict Iris Species", type="primary"):
    input_df = pd.DataFrame(
        [{
            "sepal_length": sepal_length,
            "sepal_width": sepal_width,
            "petal_length": petal_length,
            "petal_width": petal_width,
        }]
    )

    prediction_index = model.predict(input_df[FEATURE_COLUMNS])[0]
    predicted_species = target_names[int(prediction_index)]

    st.success(f"Prediction: {predicted_species}")

    if accuracy is not None:
        st.metric("Model Accuracy", f"{accuracy * 100:.2f}%")

    st.caption("Prediction generated by the trained Random Forest model using the input measurements.")

st.markdown("---")

col_model, col_dataset = st.columns(2)
with col_model:
    with st.expander("About the Model"):
        st.write("Algorithm: Random Forest Classifier")
        st.write("Dataset: Iris Dataset")
        st.write("Features: 4")
        st.write("Classes: 3")
        st.write("Deployment: Streamlit Community Cloud")
        if accuracy is not None:
            st.write(f"Training Accuracy: {accuracy * 100:.2f}%")
with col_dataset:
    with st.expander("About the Iris Dataset"):
        st.write(
            "The Iris dataset contains four flower measurements used to classify plant species: "
            "sepal length, sepal width, petal length, and petal width."
        )
        st.write("The model predicts one of the following species:")
        st.write("- Setosa")
        st.write("- Versicolor")
        st.write("- Virginica")

st.info(
    "This project demonstrates a complete ML workflow: data loading, preprocessing, model training, evaluation, saving, and deployment through a web application."
)
